// Self-contained synthesized audio; no downloads or autoplay before interaction.
export function createAudio() {
  let context=null,master=null,drone=null,droneGain=null,enabled=true;
  const active=new Set();
  function init(){if(context)return;if(typeof window==='undefined')return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;context=new AC();master=context.createGain();master.gain.value=enabled?.28:0;master.connect(context.destination);drone=context.createOscillator();drone.type='sawtooth';drone.frequency.value=45;const filter=context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=150;droneGain=context.createGain();droneGain.gain.value=0;drone.connect(filter);filter.connect(droneGain);droneGain.connect(master);drone.start();}
  function tone(freq,end,duration,volume=.1,type='sine'){if(!context||!enabled)return;const osc=context.createOscillator(),gain=context.createGain(),t=context.currentTime;osc.type=type;osc.frequency.setValueAtTime(freq,t);osc.frequency.exponentialRampToValueAtTime(Math.max(10,end),t+duration);gain.gain.setValueAtTime(volume,t);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(master);osc.start();osc.stop(t+duration+.02);active.add(osc);osc.onended=()=>{active.delete(osc);osc.disconnect();gain.disconnect();};}
  function noise(duration,volume=.15){if(!context||!enabled)return;const n=Math.floor(context.sampleRate*duration),buffer=context.createBuffer(1,n,context.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n)**2;const src=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=700;gain.gain.value=volume;src.connect(filter);filter.connect(gain);gain.connect(master);src.start();active.add(src);src.onended=()=>{active.delete(src);src.disconnect();filter.disconnect();gain.disconnect();};}
  return {unlock(){init();context?.resume().catch(()=>{});},setEnabled(v){enabled=v;if(master)master.gain.setTargetAtTime(v?.28:0,context.currentTime,.08);},update(speed,playing){if(drone){drone.frequency.setTargetAtTime(32+speed*.64,context.currentTime,.2);droneGain.gain.setTargetAtTime(playing?.028:0,context.currentTime,.15);}},event(kind){if(kind==='fire')tone(800,180,.12,.05,'triangle');if(kind==='hit')tone(170,65,.12,.035,'square');if(kind==='explosion'){noise(.55,.25);tone(65,24,.6,.22);}if(kind==='damage'){noise(.35,.16);tone(85,45,.3,.12,'sawtooth');}if(kind==='repair'){tone(550,820,.25,.1);tone(825,1100,.45,.06);}if(kind==='pulse'){noise(1,.19);tone(55,900,.8,.16);}if(kind==='warp'){tone(90,2400,2.8,.13,'sawtooth');noise(3,.13);}if(kind==='finish')tone(330,660,.6,.09);},dispose(){active.forEach(s=>{try{s.stop();}catch{}});if(drone)drone.stop();context?.close();}};
}
