'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, Crosshair, Expand, Gauge, Maximize2, Orbit, Pause, Play, RotateCcw, Shield, Volume2, VolumeX, X, Zap } from 'lucide-react';
type Status = { mode: string; health: number; energy: number; heat: number; score: number; kills: number; distance: number; speed: number; time: number; combo: number; notice: string; phase: string; pulse: number; fps: number; best: number };
type Engine = { action: (name: string, value?: unknown) => void; dispose: () => void };
const initial: Status = { mode: 'hangar', health: 100, energy: 100, heat: 0, score: 0, kills: 0, distance: 0, speed: 0, time: 0, combo: 0, notice: '', phase: '穿越碎星带', pulse: 0, fps: 60, best: 0 };
export default function Home() {
  const viewport = useRef<HTMLDivElement>(null), engine = useRef<Engine | null>(null);
  const [ready, setReady] = useState(false), [error, setError] = useState(''), [hud, setHud] = useState<Status>(initial);
  const [help, setHelp] = useState(false), [sound, setSound] = useState(true), [quality, setQuality] = useState('high');
  const [palette, setPalette] = useState('ceramic'), [free, setFree] = useState(false), [boot, setBoot] = useState('正在接通舰载系统');
  useEffect(() => {
    let stopped = false;
    import('../game/engine.mjs').then(async ({ createGame }) => {
      if (stopped || !viewport.current) return;
      const game = await createGame(viewport.current, (state: Status) => { if (!stopped) setHud(state); }, (text: string) => { if (!stopped) setBoot(text); });
      if (stopped) game.dispose(); else { engine.current = game; setReady(true); }
    }).catch((e: Error) => { if (!stopped) setError(e.message || '渲染器初始化失败'); });
    return () => { stopped = true; engine.current?.dispose(); engine.current = null; };
  }, []);
  const act = (name: string, value?: unknown) => engine.current?.action(name, value);
  const start = () => { setHelp(false); setFree(false); act('start'); };
  const isHangar = hud.mode === 'hangar', isResult = hud.mode === 'won' || hud.mode === 'lost';
  return <main className={`game-shell ${isHangar ? 'in-hangar' : 'in-flight'} ${free ? 'clean-view' : ''}`}>
    <div ref={viewport} className="viewport" aria-label="星舰三维场景" /><div className="screen-shade" />
    <header className="topbar">
      <a className="brand" href="/" aria-label="星隙首页"><span className="brand-mark">N</span><span>NACRE<span className="brand-sub">星 隙 · 深 空 行 动</span></span></a>
      <div className="top-center"><span className="live-dot" />{isHangar ? '舰桥链路已建立' : hud.mode === 'paused' ? '任务暂停' : '远航遥测在线'}<span className="separator">/</span><span className="mono">SECTOR 07</span></div>
      <div className="top-actions"><button className="icon-button" onClick={() => { setSound(!sound); act('sound', !sound); }} aria-label={sound ? '关闭音效' : '打开音效'}>{sound ? <Volume2 size={18} /> : <VolumeX size={18} />}</button><button className="icon-button" onClick={() => act('fullscreen')} aria-label="切换全屏"><Maximize2 size={18} /></button><button className="help-button" onClick={() => { if (!help && hud.mode === 'playing') act('pause'); setHelp(!help); }}>操作指南 <span>?</span></button>{!isHangar && !isResult && <button className="icon-button" onClick={() => act('pause')} aria-label={hud.mode === 'paused' ? '继续游戏' : '暂停游戏'}>{hud.mode === 'paused' ? <Play size={18} /> : <Pause size={18} />}</button>}</div>
    </header>
    {isHangar && <>
      <section className="hangar-intro"><div className="eyebrow"><span className="tiny-line" /> NACRE EXPEDITION / 001</div><h1>向未知，<br /><span>全速前进。</span></h1><p className="intro-copy">驾驶「游隼」穿越碎星带。<br />突破封锁，把最后的星图带回家。</p><div className="mission-badge"><Orbit size={15} /><span>一场 3 分钟的深空突围</span></div></section>
      <aside className="ship-specs"><div className="eyebrow">YOUR VESSEL</div><h2>游隼 <span>MK. IV</span></h2><div className="vessel-type">PEREGRINE · 长程护航舰</div><div className="spec-row"><span>舰体长度</span><strong>42.8 <small>m</small></strong></div><div className="spec-row"><span>主推进器</span><strong>双联离子引擎</strong></div><div className="spec-row"><span>武装系统</span><strong>双轨脉冲炮</strong></div><div className="spec-row"><span>防御系统</span><strong>相位冲击波</strong></div><div className="hull-status"><Shield size={14} /><span>全系统就绪</span><span className="mono">100%</span></div></aside>
      <div className="model-caption"><span>+</span><span>P–04 <em>/</em> PEREGRINE</span><span className="caption-rule" /></div>
      <div className="hangar-bottom"><section className="appearance"><div className="eyebrow">HULL FINISH <span>舰体涂装</span></div><div className="swatches">{[{ id: 'ceramic', label: '霜白陶瓷', color: '#d7e2df' }, { id: 'graphite', label: '石墨暗影', color: '#445567' }, { id: 'rescue', label: '日冕橙', color: '#d46d38' }].map(p => <button key={p.id} className={`swatch ${palette === p.id ? 'selected' : ''}`} onClick={() => { setPalette(p.id); act('palette', p.id); }} title={p.label} aria-label={p.label} aria-pressed={palette === p.id}><span style={{ background: p.color }}>{palette === p.id && <Check size={13} />}</span></button>)}<span className="finish-label">{palette === 'ceramic' ? '霜白陶瓷' : palette === 'graphite' ? '石墨暗影' : '日冕橙'}</span></div><button className="model-view-button" onClick={() => { setFree(!free); act('inspect', !free); }}><Expand size={14} />{free ? '返回舰桥' : '自由鉴赏'}<ArrowUpRight size={14} /></button></section><div className="orbit-hint"><Orbit size={17} /><span>拖动旋转舰船 · 滚轮缩放</span></div><div className="launch-block"><span className="mission-coordinates mono">KEPLER BELT<span>28° 41′ N / 07° 09′ E</span></span><button className="launch-button" disabled={!ready} onClick={start}><span><span className="launch-sub">OPERATION STARDUST</span><strong>{ready ? '启动深空突围' : '舰载系统启动中'}</strong></span><ArrowUpRight size={27} /></button><div className="launch-foot"><span className="live-dot" />单人任务<span>WASD / 鼠标 / 触屏</span></div></div></div>
    </>}
    {!isHangar && <>
      <section className="flight-mission"><div className="eyebrow">OPERATION STARDUST</div><h2>{hud.phase}</h2><div className="route-track"><span style={{ width: `${Math.min(100, hud.distance / 60)}%` }} /></div><div className="route-steps"><span className={hud.distance < 1800 ? 'active' : ''}>01 穿越</span><span className={hud.distance >= 1800 && hud.distance < 3900 ? 'active' : ''}>02 突围</span><span className={hud.distance >= 3900 ? 'active' : ''}>03 跃迁</span></div><div className="objective">抵达跃迁点 <strong>{Math.min(100, Math.floor(hud.distance / 60))}%</strong><span>击落敌机 <strong>{hud.kills}/12</strong></span></div></section>
      <section className="score-panel"><div className="eyebrow">MISSION SCORE</div><strong className="score-number mono">{String(hud.score).padStart(6, '0')}</strong><div className="score-meta mono">{Math.floor(hud.time / 60).toString().padStart(2, '0')}:{Math.floor(hud.time % 60).toString().padStart(2, '0')}<span>{hud.combo > 1 ? `${hud.combo} 连击` : 'PEREGRINE / P–04'}</span></div></section>
      <div className="reticle" aria-hidden="true"><i /></div>{hud.notice && <div className="flight-notice" role="status">{hud.notice}</div>}
      <div className="flight-bottom"><div className="ship-vitals"><div className="vital"><div><Shield size={15} /><span>舰体完整度</span><strong className={hud.health < 30 ? 'danger' : ''}>{Math.ceil(hud.health)}<small>%</small></strong></div><div className="meter"><span className={hud.health < 30 ? 'low' : ''} style={{ width: `${hud.health}%` }} /></div></div><div className="vital"><div><Zap size={15} /><span>推进能量</span><strong>{Math.floor(hud.energy)}<small>%</small></strong></div><div className="meter energy"><span style={{ width: `${hud.energy}%` }} /></div></div></div><div className="speed-panel"><Gauge size={16} /><strong className="mono">{Math.round(hud.speed * 8.6)}</strong><span>M / S</span><div className="speed-caption">{hud.speed > 44 ? 'AFTERBURNER' : 'CRUISE VELOCITY'}</div></div><div className="weapons-panel"><button className="pulse-button" onClick={() => act('pulse')} disabled={hud.pulse > 0 || hud.mode !== 'playing'}><span className="keycap">Q</span><span>相位冲击波<small>{hud.pulse > 0 ? `${Math.ceil(hud.pulse)}s 后就绪` : '已就绪 · 清除附近威胁'}</small></span><Orbit size={24} /></button><div className="heat-line"><span>炮管温度</span><div className="meter heat"><span style={{ width: `${hud.heat}%` }} /></div><span>{Math.round(hud.heat)}%</span></div></div></div>
      <div className="flight-keybar"><span><kbd>W A S D</kbd> 移动</span><span><kbd>空格</kbd> / 按住鼠标 开火</span><span><kbd>Shift</kbd> 加速</span><button onClick={() => act('camera')}><kbd>C</kbd> 切换视角</button><span><kbd>Esc</kbd> 暂停</span></div>
      <div className="touch-controls"><div className="touch-stick" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); act('touchMove', { x: 0, y: 0 }); }} onPointerMove={e => { if (!e.currentTarget.hasPointerCapture(e.pointerId)) return; const r = e.currentTarget.getBoundingClientRect(); act('touchMove', { x: (e.clientX - r.left - r.width / 2) / (r.width / 2), y: -(e.clientY - r.top - r.height / 2) / (r.height / 2) }); }} onPointerUp={() => act('touchMove', null)} onPointerCancel={() => act('touchMove', null)}><Crosshair size={36} /><span>移动</span></div><div className="touch-actions"><button aria-label="加速" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); act('touchBoost', true); }} onPointerUp={() => act('touchBoost', false)} onPointerCancel={() => act('touchBoost', false)}><Zap size={24} /></button><button className="touch-fire" aria-label="开火" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); act('touchFire', true); }} onPointerUp={() => act('touchFire', false)} onPointerCancel={() => act('touchFire', false)}><Crosshair size={32} /></button></div></div>
    </>}
    <footer className="system-footer"><span className="mono">NACRE FLIGHT SYSTEMS <span className="footer-dim">/</span> V.1.0</span><div><button onClick={() => { const next = quality === 'high' ? 'low' : 'high'; setQuality(next); act('quality', next); }}>{quality === 'high' ? '高画质' : '流畅模式'}</button><span className="fps-dot" /><span className="mono">{hud.fps} FPS</span></div></footer>
    {!ready && !error && <div className="boot-screen"><div className="boot-symbol">N</div><div className="eyebrow">PEREGRINE / SYSTEM BOOT</div><h2>{boot}</h2><div className="boot-progress"><span /></div></div>}
    {error && <div className="modal-backdrop"><section className="dialog"><div className="eyebrow">RENDER SYSTEM</div><h2>暂时无法启动三维场景</h2><p>请使用支持 WebGL 2 的新版 Chrome 或 Edge，并启用浏览器硬件加速。</p><p className="error-detail">{error}</p><button className="primary-button" onClick={() => window.location.reload()}>重新连接</button></section></div>}
    {(help || hud.mode === 'paused') && <div className="modal-backdrop"><section className="dialog controls-dialog"><button className="dialog-close" aria-label="关闭操作指南" onClick={() => { setHelp(false); if (hud.mode === 'paused') act('pause'); }}><X size={21} /></button><div className="eyebrow">FLIGHT MANUAL / 01</div><h2>{hud.mode === 'paused' ? '航行已暂停' : '准备好，舰长。'}</h2><p>躲开陨石，击落至少 12 架无人机并抵达 6,000 米外的跃迁点。穿过青色导航环可修复舰体、补充能量。</p><div className="control-list"><div><kbd>W A S D</kbd><span>上下左右移动 · 方向键亦可</span></div><div><kbd>鼠标 / 空格</kbd><span>移动鼠标瞄准 · 按住开火</span></div><div><kbd>Shift</kbd><span>消耗能量开启加力推进</span></div><div><kbd>Q</kbd><span>相位冲击波 · 清除附近威胁</span></div><div><kbd>C</kbd><span>切换追尾 / 座舱视角</span></div><div><kbd>Esc</kbd><span>暂停 / 继续任务</span></div></div><p className="help-tip">手机与平板：左侧摇杆移动，右侧准星开火，闪电按钮加速。松开开火可为炮管降温。</p><button className="primary-button" onClick={() => { setHelp(false); if (hud.mode === 'paused') act('pause'); }}>{hud.mode === 'paused' ? '继续任务' : '明白，舰长就位'}<ChevronRight size={18} /></button>{hud.mode === 'paused' && <button className="text-button" onClick={() => { setHelp(false); act('hangar'); }}>结束本次任务，返回舰桥</button>}</section></div>}
    {isResult && <div className="modal-backdrop result-backdrop"><section className="dialog result-dialog"><div className="eyebrow">MISSION {hud.mode === 'won' ? 'COMPLETE' : 'REPORT'}</div><div className="result-emblem">{hud.mode === 'won' ? <Orbit size={54} /> : <Shield size={48} />}</div><h2>{hud.mode === 'won' ? '星光，终有归途。' : '信号中断。'}</h2><p>{hud.mode === 'won' ? '跃迁成功。星图已安全送达，欢迎回家，舰长。' : '游隼号已失去动力。重整航线，再次向星空出发。'}</p><div className="result-stats"><div><span>任务得分</span><strong className="mono">{hud.score.toLocaleString()}</strong></div><div><span>击落目标</span><strong className="mono">{hud.kills}</strong></div><div><span>任务用时</span><strong className="mono">{Math.floor(hud.time / 60)}′ {Math.floor(hud.time % 60)}″</strong></div></div><div className="personal-best">本机最佳纪录 <strong>{hud.best.toLocaleString()}</strong></div><button className="primary-button" onClick={start}><RotateCcw size={17} />再次出航</button><button className="text-button" onClick={() => act('hangar')}>返回舰桥</button></section></div>}
  </main>;
}
